matrix:
  fast_finish: true
  allow_failures:
    - CHANNEL: nightly
    - TARGET: i686-pc-windows-gnu
    - TARGET: i686-pc-windows-msvc

environment:
  matrix:
    - TARGET: x86_64-pc-windows-gnu
      CHANNEL: nightly-2019-11-25
    - TARGET: x86_64-pc-windows-msvc
      CHANNEL: nightly-2019-11-25
    - TARGET: i686-pc-windows-gnu
      CHANNEL: nightly-2019-11-25
    - TARGET: i686-pc-windows-msvc
      CHANNEL: nightly-2019-11-25

    - TARGET: x86_64-pc-windows-gnu
      CHANNEL: nightly
    - TARGET: x86_64-pc-windows-msvc
      CHANNEL: nightly
    - TARGET: i686-pc-windows-gnu
      CHANNEL: nightly
    - TARGET: i686-pc-windows-msvc
      CHANNEL: nightly

install:
  - curl -sSf -o rustup-init.exe https://win.rustup.rs
  - rustup-init.exe --default-host %TARGET% --default-toolchain %CHANNEL% -y
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - rustup component add clippy rustfmt

  - rustc -Vv
  - cargo -V
  - cargo clippy -V
  - cargo fmt --version

build: false
shallow_clone: true

test_script:
  - cargo test --no-default-features
  - cargo clippy --no-default-features --verbose
  - cargo fmt -- --check

branches:
  only:
    - master
    - /^v\d+\.\d+\.\d+.*$/

cache:
  - target
  - C:\Users\appveyor\.cargo\registry

