language: rust

cache: cargo

rust:
  - nightly-2019-11-25
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - rust: nightly

before_script:
  - rustup component add clippy
  - rustup component add rustfmt

script:
  - cargo test
  - cargo clippy
  - cargo fmt -- --check

git:
  depth: 1

notifications:
  email:
    on_success: never

