language: rust

cache: cargo

rust:
  - nightly-2018-05-30

before_script:
  - cargo install clippy --force
  - cargo install rustfmt-nightly --force

script:
  - cargo test
  - cargo clippy
  - cargo fmt -- --write-mode diff

git:
  depth: 1

notifications:
  email:
    on_success: never
