language: rust

cache: cargo

rust:
  - nightly-2019-11-24
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - rust: nightly

before_script:
  - rustup component add clippy-preview
  - cargo install rustfmt-nightly --force

script:
  - cargo test
  - cargo clippy
  - cargo fmt -- --check

git:
  depth: 1

notifications:
  email:
    on_success: never

